pipeline:
  build:
    image: docker:stable
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t zookeeper .
    when:
      event: [push, tag]

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+docker_zookeeper
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/zookeeper
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event: push

  tag_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+docker_zookeeper
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/zookeeper
    tags:
      - ${DRONE_TAG}
    when:
      event: tag