---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-2
  labels:
    name: zookeeper-2
    service: zookeeper
    zookeeper_id: "2"
spec:
  type: NodePort
  ports:
    - name: client
      port: 2181
    - name: follower
      port: 2888
    - name: election
      port: 3888
  clusterIP: 10.200.10.32
  type: ClusterIP
  selector:
    name: zookeeper-2
    zookeeper_id: "2"
